FROM golang:alpine as build
WORKDIR /go/bin
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o openport main.go

FROM scratch
COPY --from=build /go/bin/openport /go/bin/openport
CMD ["./go/bin/openport"]
EXPOSE 9000
